[
    {
      name: "Dr. John Smith",
      email: "john.smith@gmail.com",
      age: 35,
      experience: "10 years",
      specialization: "Cardiology",
      description: "Experienced cardiologist with a passion for helping patients improve their heart health.",
      profileImg: "https://example.com/profiles/john-smith.jpg",
      appointmentFee: 150,
      password: "password123",
      confirmPassword: "password123"
    },
    {
      name: "Dr. Anna Lee",
      email: "anna.lee@gmail.com",
      age: 42,
      experience: "15 years",
      specialization: "Dermatology",
      description: "Board-certified dermatologist with expertise in diagnosing and treating skin conditions.",
      profileImg: "https://example.com/profiles/anna-lee.jpg",
      appointmentFee: 200,
      password: "password456",
      confirmPassword: "password456"
    },
    {
      name: "Dr. David Kim",
      email: "david.kim@gmail.com",
      age: 50,
      experience: "20 years",
      specialization: "Oncology",
      description: "Expert oncologist with a track record of successfully treating cancer patients.",
      profileImg: "https://example.com/profiles/david-kim.jpg",
      appointmentFee: 250,
      password: "password789",
      confirmPassword: "password789"
    },
    {
      name: "Dr. Sarah Patel",
      email: "sarah.patel@gmail.com",
      age: 38,
      experience: "12 years",
      specialization: "Pediatrics",
      description: "Compassionate pediatrician who provides personalized care for children of all ages.",
      profileImg: "https://example.com/profiles/sarah-patel.jpg",
      appointmentFee: 175,
      password: "passwordabc",
      confirmPassword: "passwordabc"
    },
    {
      name: "Dr. Michael Chen",
      email: "michael.chen@gmail.com",
      age: 45,
      experience: "18 years",
      specialization: "Neurology",
      description: "Neurologist who is dedicated to improving the quality of life for patients with neurological disorders.",
      profileImg: "https://example.com/profiles/michael-chen.jpg",
      appointmentFee: 225,
      password: "passworddef",
      confirmPassword: "passworddef"
    },
    {
      name: "Dr. Emily Jones",
      email: "emily.jones@gmail.com",
      age: 37,
      experience: "14 years",
      specialization: "Obstetrics and Gynecology",
      description: "OB/GYN who provides compassionate and personalized care to women throughout all stages of life.",
      profileImg: "https://example.com/profiles/emily-jones.jpg",
      appointmentFee: 190,
      password: "passwordghi",
      confirmPassword: "passwordghi"
    },
    {
      name: "Dr. Robert Davis",
      email: "robert.davis@gmail.com",
      age: 55,
      experience: "25 years",
      specialization: "Orthopedics",
      description: "Orthopedic surgeon who specializes in joint replacement and sports medicine.",
      profileImg: "https://example.com/profiles/robert-davis.jpg",
      appointmentFee: 300,
      password: "passwordjkl",
      confirmPassword: "passwordjkl"
    },
    {
        name: "Dr. John Doe",
        email: "johndoe@example.com",
        age: 38,
        experience: "10 years",
        specialization: "Cardiology",
        description: "I am a highly skilled cardiologist with a passion for saving lives.",
        profileImg: "https://example.com/johndoe.jpg",
        appointmentFee: 1500,
        password: "mypassword",
        confirmPassword: "mypassword"
      },
      {
        name: "Dr. Jane Smith",
        email: "janesmith@example.com",
        age: 42,
        experience: "15 years",
        specialization: "Dermatology",
        description: "I am a board-certified dermatologist with expertise in treating skin conditions.",
        profileImg: "https://example.com/janesmith.jpg",
        appointmentFee: 2000,
        password: "mypassword",
        confirmPassword: "mypassword"
      },
      {
        name: "Dr. Mark Johnson",
        email: "markjohnson@example.com",
        age: 45,
        experience: "20 years",
        specialization: "Neurology",
        description: "I am a highly experienced neurologist with a passion for helping patients with neurological disorders.",
        profileImg: "https://example.com/markjohnson.jpg",
        appointmentFee: 2500,
        password: "mypassword",
        confirmPassword: "mypassword"
      },
      {
        name: "Dr. Sarah Lee",
        email: "sarahlee@example.com",
        age: 39,
        experience: "12 years",
        specialization: "Pediatrics",
        description: "I am a caring and compassionate pediatrician with expertise in treating children of all ages.",
        profileImg: "https://example.com/sarahlee.jpg",
        appointmentFee: 1800,
        password: "mypassword",
        confirmPassword: "mypassword"
      },
      {
        name: "Dr. Robert Kim",
        email: "robertkim@example.com",
        age: 50,
        experience: "25 years",
        specialization: "Oncology",
        description: "I am a highly skilled oncologist with expertise in treating cancer patients.",
        profileImg: "https://example.com/robertkim.jpg",
        appointmentFee: 3000,
        password: "mypassword",
        confirmPassword: "mypassword"
      },
      {
        name: "Dr. Laura Martinez",
        email: "lauramartinez@example.com",
        age: 35,
        experience: "8 years",
        specialization: "Gynecology",
        description: "I am a board-certified gynecologist with expertise in women's health.",
        profileImg: "https://example.com/lauramartinez.jpg",
        appointmentFee: 1500,
        password: "mypassword",
        confirmPassword: "mypassword"
      },
      {
        name: "Dr. William Jones",
        email: "williamjones@example.com",
        age: 48,
        experience: "18 years",
        specialization: "Orthopedics",
        description: "I am a highly skilled orthopedic surgeon with expertise in treating musculoskeletal injuries.",
        profileImg: "https://example.com/williamjones.jpg",
        appointmentFee: 2800,
        password: "mypassword",
        confirmPassword: "mypassword"
      },
        {
          name: "Dr. John Doe",
          email: "johndoe@gmail.com",
          age: 42,
          experience: "10 years",
          specialization: "Cardiologist",
          description: "I have extensive experience in diagnosing and treating heart diseases.",
          profileImg: "https://example.com/profile/123",
          appointmentFee: 1500,
          password: "strongPassword123",
          confirmPassword: "strongPassword123"
        },
        {
          name: "Dr. Jane Smith",
          email: "janesmith@yahoo.com",
          age: 35,
          experience: "8 years",
          specialization: "Pediatrician",
          description: "I love working with children and providing compassionate care to their families.",
          profileImg: "https://example.com/profile/456",
          appointmentFee: 1200,
          password: "securePassword456",
          confirmPassword: "securePassword456"
        },
        {
          name: "Dr. David Kim",
          email: "davidkim@hotmail.com",
          age: 50,
          experience: "15 years",
          specialization: "Orthopedic Surgeon",
          description: "I specialize in joint replacement surgeries and have a high success rate.",
          profileImg: "https://example.com/profile/789",
          appointmentFee: 2000,
          password: "password123",
          confirmPassword: "password123"
        },
        {
          name: "Dr. Sarah Lee",
          email: "sarahlee@gmail.com",
          age: 38,
          experience: "12 years",
          specialization: "Dermatologist",
          description: "I am passionate about helping people achieve healthy and beautiful skin.",
          profileImg: "https://example.com/profile/101",
          appointmentFee: 1800,
          password: "strongPassword789",
          confirmPassword: "strongPassword789"
        },
        {
          name: "Dr. Michael Chen",
          email: "michaelchen@yahoo.com",
          age: 45,
          experience: "10 years",
          specialization: "Ophthalmologist",
          description: "I specialize in eye surgeries and have helped many patients regain their vision.",
          profileImg: "https://example.com/profile/112",
          appointmentFee: 2500,
          password: "securePassword101",
          confirmPassword: "securePassword101"
        },
        {
          name: "Dr. Lisa Park",
          email: "lisapark@hotmail.com",
          age: 40,
          experience: "10 years",
          specialization: "Psychiatrist",
          description: "I help my patients manage their mental health and improve their quality of life.",
          profileImg: "https://example.com/profile/131",
          appointmentFee: 1500,
          password: "password456",
          confirmPassword: "password456"
        },
        {
          name: "Dr. William Chang",
          email: "williamchang@gmail.com",
          age: 55,
          experience: "20 years",
          specialization: "Neurologist",
          description: "I diagnose and treat conditions affecting the nervous system.",
          profileImg: "https://example.com/profile/141",
          appointmentFee: 3000,
          password: "strongPassword111",
          confirmPassword: "strongPassword111"
        }
]