[
    {
      name: "John Doe",
      age: 28,
      address: "123 Main St, Anytown USA",
      bloodGroup: "O+",
      phoneNumber: 1234567890,
      email: "johndoe@example.com",
      password: "P@ssw0rd123",
      confirmPassword: "P@ssw0rd123",
      profilePhoto: "https://example.com/profile.jpg"
    },
    {
      name: "Jane Smith",
      age: 35,
      address: "456 Elm St, Anytown USA",
      bloodGroup: "B-",
      phoneNumber: 2345678901,
      email: "janesmith@example.com",
      password: "P@ssw0rd456",
      confirmPassword: "P@ssw0rd456",
      profilePhoto: "https://example.com/profile.jpg"
    },
    {
      name: "Bob Johnson",
      age: 42,
      address: "789 Oak St, Anytown USA",
      bloodGroup: "A+",
      phoneNumber: 3456789012,
      email: "bobjohnson@example.com",
      password: "P@ssw0rd789",
      confirmPassword: "P@ssw0rd789",
      profilePhoto: "https://example.com/profile.jpg"
    },
    {
      name: "Mary Brown",
      age: 26,
      address: "321 Maple St, Anytown USA",
      bloodGroup: "AB+",
      phoneNumber: 4567890123,
      email: "marybrown@example.com",
      password: "P@ssw0rd123",
      confirmPassword: "P@ssw0rd123",
      profilePhoto: "https://example.com/profile.jpg"
    },
    {
      name: "Tom Wilson",
      age: 33,
      address: "654 Birch St, Anytown USA",
      bloodGroup: "O-",
      phoneNumber: 5678901234,
      email: "tomwilson@example.com",
      password: "P@ssw0rd456",
      confirmPassword: "P@ssw0rd456",
      profilePhoto: "https://example.com/profile.jpg"
    },
    {
      name: "Samantha Lee",
      age: 29,
      address: "987 Pine St, Anytown USA",
      bloodGroup: "B+",
      phoneNumber: 6789012345,
      email: "samanthalee@example.com",
      password: "P@ssw0rd789",
      confirmPassword: "P@ssw0rd789",
      profilePhoto: "https://example.com/profile.jpg"
    },
    {
      name: "David Rodriguez",
      age: 40,
      address: "159 Cedar St, Anytown USA",
      bloodGroup: "A-",
      phoneNumber: 7890123456,
      email: "davidrodriguez@example.com",
      password: "P@ssw0rd123",
      confirmPassword: "P@ssw0rd123",
      profilePhoto: "https://example.com/profile.jpg"
    },
    {
      name: "Stephanie Kim",
      age: 24,
      address: "753 Oak St, Anytown USA",
      bloodGroup: "AB-",
      phoneNumber: 8901234567,
      email: "stephaniekim@example.com",
      password: "P@ssw0rd456",
      confirmPassword: "P@ssw0rd456",
      profilePhoto: "https://example.com/profile.jpg
    },
    {
        name: "George Smith",
        age: 35,
        address: "123 Main St, Anytown USA",
        bloodGroup: "AB+",
        phoneNumber: 1234567890,
        email: "george.smith@gmail.com",
        password: "mystrongpassword123",
        confirmPassword: "mystrongpassword123",
        profilePhoto: "https://randomuser.me/api/portraits/men/1.jpg"
      },
      {
        name: "Ava Rodriguez",
        age: 22,
        address: "456 Elm St, Anytown USA",
        bloodGroup: "A+",
        phoneNumber: 2345678901,
        email: "ava.rodriguez@yahoo.com",
        password: "password123",
        confirmPassword: "password123",
        profilePhoto: "https://randomuser.me/api/portraits/women/2.jpg"
      },
      {
        name: "Oliver Lee",
        age: 47,
        address: "789 Oak St, Anytown USA",
        bloodGroup: "O+",
        phoneNumber: 3456789012,
        email: "oliver.lee@hotmail.com",
        password: "123456789",
        confirmPassword: "123456789",
        profilePhoto: "https://randomuser.me/api/portraits/men/3.jpg"
      },
      {
        name: "Emma Hernandez",
        age: 29,
        address: "1010 Maple Ave, Anytown USA",
        bloodGroup: "B+",
        phoneNumber: 4567890123,
        email: "emma.hernandez@gmail.com",
        password: "P@ssw0rd123",
        confirmPassword: "P@ssw0rd123",
        profilePhoto: "https://randomuser.me/api/portraits/women/4.jpg"
      },
      {
        name: "Liam Nguyen",
        age: 18,
        address: "1313 Pine St, Anytown USA",
        bloodGroup: "AB-",
        phoneNumber: 5678901234,
        email: "liam.nguyen@yahoo.com",
        password: "mysecretpassword",
        confirmPassword: "mysecretpassword",
        profilePhoto: "https://randomuser.me/api/portraits/men/5.jpg"
      },
      {
        name: "Sophia Kim",
        age: 42,
        address: "1515 Cedar St, Anytown USA",
        bloodGroup: "B-",
        phoneNumber: 6789012345,
        email: "sophia.kim@hotmail.com",
        password: "password1234",
        confirmPassword: "password1234",
        profilePhoto: "https://randomuser.me/api/portraits/women/6.jpg"
      },
      {
        name: "Noah Singh",
        age: 25,
        address: "1717 Oak St, Anytown USA",
        bloodGroup: "O-",
        phoneNumber: 7890123456,
        email: "noah.singh@gmail.com",
        password: "p@$$w0rd",
        confirmPassword: "p@$$w0rd",
        profilePhoto: "https://randomuser.me/api/portraits/men/7.jpg"
      },
      {
        name: "Isabella Kim",
        age: 33,
        address: "1919 Cedar St, Anytown USA",
        bloodGroup: "A-",
        phoneNumber: 8901234567,
        email: "isabella.kim@yahoo.com",
        password: "iloveyou123",
        confirmPassword: "iloveyou123",
        profilePhoto: "https://randomuser.me/api/portraits/women/"
      },{
        name: "Emma Smith",
        age: 29,
        address: "123 Main St, Apt 3B",
        bloodGroup: "O+",
        phoneNumber: 5551112222,
        email: "emma.smith@example.com",
        password: "sFj6*Jhd92",
        confirmPassword: "sFj6*Jhd92",
        profilePhoto: "https://randomuser.me/api/portraits/women/25.jpg"
      },
      {
        name: "Ryan Johnson",
        age: 43,
        address: "456 Oak Rd",
        bloodGroup: "B-",
        phoneNumber: 5552223333,
        email: "ryan.johnson@example.com",
        password: "4tDp#KxvL7",
        confirmPassword: "4tDp#KxvL7",
        profilePhoto: "https://randomuser.me/api/portraits/men/23.jpg"
      },
      {
        name: "Sophie Brown",
        age: 31,
        address: "789 Maple Ave, Apt 5C",
        bloodGroup: "A+",
        phoneNumber: 5553334444,
        email: "sophie.brown@example.com",
        password: "Gh@3rTm8Kp",
        confirmPassword: "Gh@3rTm8Kp",
        profilePhoto: "https://randomuser.me/api/portraits/women/33.jpg"
      },
      {
        name: "David Lee",
        age: 26,
        address: "321 Elm St",
        bloodGroup: "AB-",
        phoneNumber: 5554445555,
        email: "david.lee@example.com",
        password: "jK5$bmLd7S",
        confirmPassword: "jK5$bmLd7S",
        profilePhoto: "https://randomuser.me/api/portraits/men/37.jpg"
      },
      {
        name: "Isabella Martinez",
        age: 38,
        address: "567 Pine St, Apt 2D",
        bloodGroup: "A-",
        phoneNumber: 5555556666,
        email: "isabella.martinez@example.com",
        password: "9fL#xMvT6Z",
        confirmPassword: "9fL#xMvT6Z",
        profilePhoto: "https://randomuser.me/api/portraits/women/44.jpg"
      },
      {
        name: "James Wilson",
        age: 52,
        address: "234 Cherry Ln",
        bloodGroup: "O-",
        phoneNumber: 5556667777,
        email: "james.wilson@example.com",
        password: "pR4$zKtD9L",
        confirmPassword: "pR4$zKtD9L",
        profilePhoto: "https://randomuser.me/api/portraits/men/57.jpg"
      },
      {
        name: "Emily Garcia",
        age: 24,
        address: "789 Oak St, Apt 1A",
        bloodGroup: "B+",
        phoneNumber: 5557778888,
        email: "emily.garcia@example.com",
        password: "sT7&bWkN3P",
        confirmPassword: "sT7&bWkN3P",
        profilePhoto: "https://randomuser.me/api/portraits/women/63.jpg"
      }
      
]